sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-149
env:
  global:
    -
      # LTD_AWS_ID
      secure: BNtJI7Y1fU/ud08zf26JsMZ6r3djZEYb8yj6KCWIU7XpokSwWkp/Gt37IdRgMJxLYJ/RL862tW3BaxggX8elOwAClH4loEpgsW6d+F9tU6VJMee7jGsNKN5O5g3g/GrB/j4qAf57jbJYMq5YYkgZ8PHWPbW9+T8cdD+nH1oRKDL7obOT4CfJa3df5DgEysAAcaffKCq7cjWcStl20VFufY6YdxhEyNp2r+GZXCyzQPbbipn0MtTWPqkWOf3qA2d9K1nU0UNlaMDFqStXk9RZa7E43Db/VUrsAzZI4MZal0N43CeFUJwSvQ7d7MtiVgwIDTZqSae24IKvDmZfxQFVB3cPYHsrSjc6DxzZ7wcj/ytzSsgN8fxuPB4y4tUS/KKj7RzsNGfrvsd1NjP5GTQDMz3imWBJBJ/cft5/2l5Ts+XVK0pb9yhkqezPnvIKNvkXZCHKTX7LL4v5m8Gc3r9lT8MWaCrdZpp7JMMZx1fCIMlTdATYs6YmW1mWcxuhtqPK9n3gk8l8laaaeQ+ebPMvwpyawFjcvaUZpjEH8etgKuX0zswrBmalkfdRS+0asyFyW75qy83K/vcFaMN16I6py0p6a/pb/YvVArPcf/LOqnw9QpOxfar+yvPgWO62VG+5LtE9nW84fnnZwluZ7KFOWNpxV7TXzpk4nRlMVKnLuyI=
    -
      # LTD_AWS_SECRET
      secure: pUGHEG5JtByKm/b6GR5QP5Klzz+eVk6lWN+FK/p8rbPM+rGOrQRO/INDVBiOfR7jqReG58VcYKJw8dJTtGxS2Lf0FCS62qqaIxpKCTowoAU3GSSJhY7hxQAoEZUNULP+EWSujLwUXR/TRrhsfEPP6LJUjUgp0AmQvyCLGVD/4k39pHnck/FNcjWXIyFciUs8q3UVB+8Er/UIXMF8N6gRGw4WxUufwYjJcLvsAGO36o54/+pXSwwf7J94vP7zUS53AUr3oksM0WlCg82J2kYQTcGe2OGijqYtOwbz+t/naLmMQf75yUE/iO+7fmIx26s2qo9+YiF84N4fVI6DIUeKRzJTV8rc3XJA59xSq0ImBIRw2/Z/7PIDOp6Cr+clGbYoob2IbErbR9Og16fAyCcdjKwYbbtrHrgaCB2zE4RtW+S6F+i0gAVyGsBcTj9BH8CXRU0k8vNIcvunSwHo7VTtWbZR7tO/BEY9ghdAjWKS7pM0/tHZkLkgTZ7+31hZ23brbQwnQe/PQoQg/aSCPqEfnCfD2zQIOwTD0Km0SmU1z69QKrd5kOEaT2QW+8ulj61nuCWa1kXdVuXbRcGAE6hEwNo+NXpAQ9QQTlUFGx1eI6NMyX4uJuQSHcOdaUb9stHJ7V0N9I1WWCLL9WnHJFesjPx7DRAgDeaBZF/YIGUYano=
    -
      # LTD_USERNAME
      secure: FRGsM0HPvVS6bNYir2FY7Neb9xaAhLhXGB2FqrsZW+2pkW1G2SPEmhjnF3YB7M9672wvB6uXuinO3VTWosRzsPi3khLzvUwNWrbCva4oZUl6+lLY5UpMwqxXieKFqgTY0qSldsmZecEagoFVuwLN0ddFxeSFq4ACetvVPmg8cBGl7HDCFWKIcgjB//llLXh5gct+97CqeFQZw7rnXIOMl/VD+AtQ7h6E5g9Pl8H0azFoREEHrgApHbyp2MrBOwvG1UE0/c2lBxKgF+ey53ikMj57W4f5vuBojrZirc+ZO/yM6vavZLzlo4Z5bnrzxiQ4EV8TLnXneZ7FLUJ9YFB+RQb5yUm5ShpTGY5Fqs4poD4BCsWW1rCCCcQ9rcCoei7hEu4LrezjfUtTpL88XeqgpkR6X6k9JVMQSjdZvFtKU6KyK83679d6k/7SJUt9T9iycRPyPci3c+BQEmKeI15PCkrpKTOan8Hn80OkJZQAHl5nW8Bzo9c8z2sRg6wAxciq9GZ+8WIvTO6hm/bkDmoKOBikNd/evX6POkRjAc997V8Ooate1ifgMipMXd68RBBH/DoolTZhf83VVsjR3r3xKM6vvodQSop/mjvF5rG5gWsycyjkaV+cWRyHhwujRsnAyU9j1hSpEmKns6mjN8w/bP0Mi3gJYR2y4tk1AQcrhpI=
    -
      # LTD_PASSWORD
      secure: Lk26d8Ds3Qt+C0fihh8GZkgd/P+XrcvTXwJGt3ekuYCPu0FP3D57lXAxt6fV79ATFIBZtYflT10UZeVPQIXlcytNDKwt4d6NoAtbkjft454Dp8sdVVdHTesNLx9izMmD3pJBCxVlvbkMjv9Hf0F2YPHKotaMB+xIgzuLHIFADROWW0mmB+nQ9U3prx0d8I7F4R+i8/AAzRhgR57I4ycbBEK0D/bwdQ/Zn5il1xbfZ9nHw66+e9jYgMYTHTCE0fMLFdPCHalxDlLJoSU5QOoxta3SR4DD6InUHrImBJhh4Fgw4V2PtAdohbkWdu2uUImpMirUfOtN6v8Xx4nNsTqSkI7xNNTPSVsWA7M8ZVuhoHPU8pUvwoqbew9n0WqOYtW9GGV46Frc6xL6wA4VaskmmGvrVLBqN9Wiuz5bkB/UqRIZPRJq8efJzD75oU12z78Wr4Fyz8pvqnimqFBFPgLld/FYyuMf/RwxCe+KfvHsT6A6x7siSCuL/3PNVZGqCyeN0u3Z0Np18zhtp/uQ1XCJiFqT6PzA8JIRUV3JnPwhuzy+YsG7QE0jbymSq54QcgOlzLNFgGu/44go7Q9xZkHGijz79epoifq90xaL6pbr3UT3jI3JiVAK4q3ZZf6LKtpQVRJDbjTYqWFcYfDXwi2Gs2xpff4ChrVkK0l3zS9fWso=
